# User Settings | Edit there as per required

title: Mayra Cabrera's Blog
url: "http://mayra-cabrera.github.io"
baseurl: #"/"

# This will show up at the top of index page
site_heading: >
    Mayra<span class="faded">'s blog</span>

email: mcabrera1087@gmail.com
author: Mayra Cabrera
# This description will show up in google search results
# (for index page) etc.
description: >
    I like programming and cats

# This will what will show against &copy; in the footer
copyright: mayerson
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: #
permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    I like programming and cats

about_footer: true

twitter_username: may-cabrera
github_username: mayra-cabrera
linkedin_id: mayra-cabrera-2b944a80
facebook_id: #yourusername

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/may_cabrera.jpg
paginate: 5
paginate_path: "/page/:num"
#tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
#og_image: "images/accent.png" # This will show in facebook thumbnails
twitter_image: "https://pbs.twimg.com/profile_images/673653235920408576/PDRYrchH.jpg" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
